springdoc:
  swagger-ui:
    path: /

application:
  jwt:
    claim-user-email: userEmail
    claim-user-scopes: scope
    token-expiration-after-days: 3
    token-prefix: Bearer
    secret-key: secret-key-sample-to-use-secret-key-sample-to-use

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

# Default Config
server:
  email: default@gmail.com

---
# Dev Config
spring:
  profiles: dev
server:
  email: dev@gmail.com

---
# Prod Config
spring:
  profiles: prod
server:
  email: prod@gmail.com