springdoc:
  swagger-ui:
    path: /

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

# Default Config
server:
  email: default@gmail.com

---
# Dev Config
spring:
  profiles: dev
server:
  email: dev@gmail.com

---
# Prod Config
spring:
  profiles: prod
server:
  email: prod@gmail.com